### ISSUE TITLE
Adding a quote in firefox 53.0 64 bit, automatically insert a backquote black line below it. 

### ISSUE THREAD

**Issue by satishck1992** [mjbp/editor#1]
Hi,
Thank you for your work :). 
I was looking to integrate the editor on one of my project. And everytime I tried to mark a line as a quote, a black BACKQUOTE line appears automatically under the line.

**Comment by mjbp** [comment]
Sorry for the terribly slow response. Thanks for showing interest in this project but I'm not currently maintaining it (and haven't been for a while).

If you're looking for a more robust medium-style editor that uses the contenteditable API I'd suggest https://github.com/yabwe/medium-editor.
